name: flutter_amplify_login
description: Example of a flutter application to use Very Good CLI and AWS Amplify auth service
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: 3.3.4

dependencies:
  amplify_auth_cognito: ^0.6.9
  amplify_flutter: ^0.6.9
  auth_client:
    path: packages/auth_client
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  generate: true
