name: auth_client
description: AWS Amplify auth client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  amplify_auth_cognito: ^0.6.8
  amplify_flutter: ^0.6.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2
