name: form_inputs
description: A Dart package which exposes reusable form inputs and validation rules
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: 3.3.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
